const stores = [
  {
    id: "icondenim-aeon-mall-ha-dong",
    name: "ICONDENIM AEON Mall - Hà Đông",
    province: "Hà Nội",
    district: "Quận Hà Đông",
    address: "Tầng 2 AEON Mall Hà Đông, Dương Nội, Hà Đông, Hà Nội",
    time: "08:30 - 22:00",
    phone: "02873066060",
    image: "/images/store/icondenim-aeon-mall-ha-dong.jpg",
    mapLink: "https://maps.google.com/?q=AEON+Mall+Ha+Dong",
    isNew: true,
    isOpen: true,
  },
  {
    id: "icondenim-aeon-mall-binh-tan",
    name: "ICONDENIM AEON Mall - Bình Tân",
    province: "Hồ Chí Minh",
    district: "Quận Bình Tân",
    address:
      "Tầng 1 AEON Mall Bình Tân, 1 Đường Số 17A, Bình Trị Đông B, Bình Tân, Hồ Chí Minh",
    time: "08:30 - 22:00",
    phone: "02873066060",
    image: "/images/store/icondenim-aeon-mall-binh-tan.jpg",
    mapLink: "https://maps.google.com/?q=AEON+Mall+Binh+Tan",
    isNew: false,
    isOpen: true,
  },
  {
    id: "icondenim-nguyen-gia-tri",
    name: "ICONDENIM Nguyễn Gia Trí",
    province: "Hồ Chí Minh",
    district: "Quận Bình Thạnh",
    address: "125 Nguyễn Gia Trí, Phường Thạnh Mỹ Tây, Bình Thạnh, Hồ Chí Minh",
    time: "08:30 - 22:00",
    phone: "02873066060",
    image: "/images/store/icondenim-nguyen-gia-tri.jpg",
    mapLink: "https://maps.google.com/?q=125+Nguyen+Gia+Tri",
    isNew: false,
    isOpen: true,
  },
  {
    id: "icondenim-chua-boc",
    name: "ICONDENIM Chùa Bộc",
    province: "Hà Nội",
    district: "Quận Đống Đa",
    address: "72 P. Chùa Bộc, Quang Trung, Quận Đống Đa, Hà Nội",
    time: "08:30 - 22:00",
    phone: "02873066060",
    image: "/images/store/icondenim-chua-boc.jpg",
    mapLink: "https://maps.google.com/?q=72+Chua+Boc",
    isNew: false,
    isOpen: true,
  },
  {
    id: "icondenim-yersin",
    name: "ICONDENIM Yersin",
    province: "Bình Dương",
    district: "TP. Thủ Dầu Một",
    address: "79 Yersin, Phường Phú Cường, Thủ Dầu Một, Bình Dương",
    time: "08:30 - 22:00",
    phone: "02873066060",
    image: "/images/store/icondenim-yersin.jpg",
    mapLink: "https://maps.google.com/?q=79+Yersin+Binh+Duong",
    isNew: false,
    isOpen: true,
  },
  {
    id: "icondenim-vo-van-ngan",
    name: "ICONDENIM Võ Văn Ngân",
    province: "Hồ Chí Minh",
    district: "TP. Thủ Đức",
    address: "96A, Võ Văn Ngân, Phường Thủ Đức, TP Hồ Chí Minh",
    time: "08:30 - 22:00",
    phone: "02873066060",
    image: "/images/store/icondenim-vo-van-ngan.jpg",
    mapLink: "https://maps.google.com/?q=96A+Vo+Van+Ngan",
    isNew: false,
    isOpen: true,
  },
  {
    id: "icondenim-nguyen-anh-thu",
    name: "ICONDENIM Nguyễn Ảnh Thủ",
    province: "Hồ Chí Minh",
    district: "Quận 12",
    address:
      "3/10 Đ. Nguyễn Ảnh Thủ, Khu phố 1, Phường Trung Mỹ Tây, TP Hồ Chí Minh",
    time: "08:30 - 22:00",
    phone: "02873066060",
    image: "/images/store/icondenim-nguyen-anh-thu.jpg",
    mapLink: "https://maps.google.com/?q=3/10+Nguyen+Anh+Thu",
    isNew: false,
    isOpen: true,
  },
  {
    id: "icondenim-nguyen-trai",
    name: "ICONDENIM Nguyễn Trãi",
    province: "Hồ Chí Minh",
    district: "Quận 5",
    address: "261, Đ. Nguyễn Trãi, Phường Chợ Quán, TP Hồ Chí Minh",
    time: "08:30 - 22:00",
    phone: "02873066060",
    image: "/images/store/icondenim-nguyen-trai.jpg",
    mapLink: "https://maps.google.com/?q=261+Nguyen+Trai",
    isNew: false,
    isOpen: true,
  },
  {
    id: "icondenim-cmt8",
    name: "ICONDENIM Cách Mạng Tháng 8",
    province: "Hồ Chí Minh",
    district: "Quận 1",
    address: "12-12Bis, CMT8, Phường Bến Thành, TP Hồ Chí Minh",
    time: "08:30 - 22:00",
    phone: "02873066060",
    image: "/images/store/icondenim-cmt8.jpg",
    mapLink: "https://maps.google.com/?q=12+CMT8",
    isNew: false,
    isOpen: true,
  },
  {
    id: "icondenim-le-van-sy",
    name: "ICONDENIM Lê Văn Sỹ",
    province: "Hồ Chí Minh",
    district: "Quận 3",
    address: "484, Lê Văn Sỹ, Phường Nhiêu Lộc, TP Hồ Chí Minh",
    time: "08:30 - 22:00",
    phone: "02873066060",
    image: "/images/store/icondenim-le-van-sy.jpg",
    mapLink: "https://maps.google.com/?q=484+Le+Van+Sy",
    isNew: false,
    isOpen: true,
  },
  {
    id: "icondenim-su-van-hanh",
    name: "ICONDENIM Sư Vạn Hạnh",
    province: "Hồ Chí Minh",
    district: "Quận 10",
    address: "477-481, Sư Vạn Hạnh, Phường Hòa Hưng, TP Hồ Chí Minh",
    time: "08:30 - 22:00",
    phone: "02873066060",
    image: "/images/store/icondenim-su-van-hanh.jpg",
    mapLink: "https://maps.google.com/?q=477+Su+Van+Hanh",
    isNew: false,
    isOpen: true,
  },
  {
    id: "icondenim-quang-trung",
    name: "ICONDENIM Quang Trung",
    province: "Hồ Chí Minh",
    district: "Quận Gò Vấp",
    address: "261, Quang Trung, Phường Gò Vấp, TP Hồ Chí Minh",
    time: "08:30 - 22:00",
    phone: "02873066060",
    image: "/images/store/icondenim-quang-trung.jpg",
    mapLink: "https://maps.google.com/?q=261+Quang+Trung",
    isNew: false,
    isOpen: true,
  },
  {
    id: "icondenim-nguyen-thi-thap",
    name: "ICONDENIM Nguyễn Thị Thập",
    province: "Hồ Chí Minh",
    district: "Quận 7",
    address: "420 Nguyễn Thị Thập, Phường Tân Hưng, TP Hồ Chí Minh",
    time: "08:30 - 22:00",
    phone: "02873066060",
    image: "/images/store/icondenim-nguyen-thi-thap.jpg",
    mapLink: "https://maps.google.com/?q=420+Nguyen+Thi+Thap",
    isNew: false,
    isOpen: true,
  },
  {
    id: "icondenim-pham-van-thuan",
    name: "ICONDENIM Phạm Văn Thuận",
    province: "Đồng Nai",
    district: "TP. Biên Hòa",
    address: "1357 Phạm Văn Thuận, Phường Biên Hòa, Đồng Nai",
    time: "08:30 - 22:00",
    phone: "02873066060",
    image: "/images/store/icondenim-pham-van-thuan.jpg",
    mapLink: "https://maps.google.com/?q=1357+Pham+Van+Thuan",
    isNew: false,
    isOpen: true,
  },
  {
    id: "icondenim-tan-son-nhi",
    name: "ICONDENIM Tân Sơn Nhì",
    province: "Hồ Chí Minh",
    district: "Quận Tân Phú",
    address: "310, Tân Sơn Nhì, Phường Tân Sơn Nhì, TP Hồ Chí Minh",
    time: "08:30 - 22:00",
    phone: "02873066060",
    image: "/images/store/icondenim-tan-son-nhi.jpg",
    mapLink: "https://maps.google.com/?q=310+Tan+Son+Nhi",
    isNew: false,
    isOpen: true,
  },
];
export default stores;
