export const stores = [
  {
    id: "icondenim-su-van-hanh",
    name: "ICONDENIM Sư Vạn Hạnh",
    province: "Hồ Chí Minh",
    district: "Quận 10",
    address: "477-481 Sư Vạn Hạnh, Phường 12, Quận 10, TP.HCM",
    time: "08:30 - 22:30",
    phone: "02873066060",
    image: "/images/store/icondenim-su-van-hanh.jpg",
    mapLink: "https://maps.app.goo.gl/sqk8hKhaWDdcCL9j9",
    isNew: false,
    isOpen: true,
  },
  {
    id: "icondenim-cmt8",
    name: "ICONDENIM CMT8",
    province: "Hồ Chí Minh",
    district: "Quận 1",
    address: "12-14 Cách Mạng Tháng Tám, P. Bến Thành, Quận 1, TP.HCM",
    time: "08:30 - 22:30",
    phone: "02873066060",
    image: "/images/store/icondenim-cmt8.jpg",
    mapLink: "https://maps.app.goo.gl/sjkRVMtH4dgMFFbA8",
    isNew: false,
    isOpen: true,
  },
  {
    id: "icondenim-nguyen-thi-thap",
    name: "ICONDENIM Nguyễn Thị Thập",
    province: "Hồ Chí Minh",
    district: "Quận 7",
    address: "420B Nguyễn Thị Thập, Tân Quy, Quận 7, TP.HCM",
    time: "08:30 - 22:30",
    phone: "02873066060",
    image: "/images/store/icondenim-nguyen-thi-thap.jpg",
    mapLink: "https://maps.app.goo.gl/BUYjF2PyRgEHg8oa7",
    isNew: false,
    isOpen: true,
  },
  {
    id: "icondenim-quang-trung",
    name: "ICONDENIM Quang Trung",
    province: "Hồ Chí Minh",
    district: "Quận Gò Vấp",
    address: "261 Quang Trung, Phường 10, Quận Gò Vấp, TP.HCM",
    time: "08:30 - 22:30",
    phone: "02873066060",
    image: "/images/store/icondenim-quang-trung.jpg",
    mapLink: "https://maps.app.goo.gl/pzMAPAFYynPWG59s6",
    isNew: false,
    isOpen: true,
  },
  {
    id: "icondenim-vo-van-ngan",
    name: "ICONDENIM Võ Văn Ngân",
    province: "Hồ Chí Minh",
    district: "TP. Thủ Đức",
    address: "96A Võ Văn Ngân, Bình Thọ, TP. Thủ Đức, TP.HCM",
    time: "08:30 - 22:30",
    phone: "02873066060",
    image: "/images/store/icondenim-vo-van-ngan.jpg",
    mapLink: "https://maps.app.goo.gl/qZZpEiYC9xV2sRWr6",
    isNew: false,
    isOpen: true,
  },
  {
    id: "icondenim-le-van-sy",
    name: "ICONDENIM Lê Văn Sỹ",
    province: "Hồ Chí Minh",
    district: "Quận 3",
    address: "484 Lê Văn Sỹ, Phường 14, Quận 3, TP.HCM",
    time: "08:30 - 22:30",
    phone: "02873066060",
    image: "/images/store/icondenim-le-van-sy.jpg",
    mapLink: "https://maps.app.goo.gl/hnXVDRebRskothh99",
    isNew: false,
    isOpen: true,
  },
  {
    id: "icondenim-nguyen-trai",
    name: "ICONDENIM Nguyễn Trãi",
    province: "Hồ Chí Minh",
    district: "Quận 5",
    address: "261 Nguyễn Trãi, Phường 2, Quận 5, TP.HCM",
    time: "08:30 - 22:30",
    phone: "02873066060",
    image: "/images/store/icondenim-nguyen-trai.jpg",
    mapLink: "https://maps.app.goo.gl/giJSmf6CAqrZPsxu6",
    isNew: false,
    isOpen: true,
  },
  {
    id: "icondenim-tan-son-nhi",
    name: "ICONDENIM Tân Sơn Nhì",
    province: "Hồ Chí Minh",
    district: "Quận Tân Phú",
    address: "310 Tân Sơn Nhì, Tân Sơn Nhì, Tân Phú, TP.HCM",
    time: "08:30 - 22:30",
    phone: "02873066060",
    image: "/images/store/icondenim-tan-son-nhi.jpg",
    mapLink: "https://maps.app.goo.gl/JMXaT9rksMeBksqK7",
    isNew: false,
    isOpen: true,
  },
  {
    id: "icondenim-hau-giang",
    name: "ICONDENIM Hậu Giang",
    province: "Hồ Chí Minh",
    district: "Quận 6",
    address: "437 Hậu Giang, Phường 11, Quận 6, TP.HCM",
    time: "08:30 - 22:30",
    phone: "02873066060",
    image: "/images/store/icondenim-hau-giang.jpg",
    mapLink: "https://maps.app.goo.gl/3jKPi5c68d7Wg1wb6",
    isNew: false,
    isOpen: true,
  },
  {
    id: "icondenim-aeon-ha-dong",
    name: "ICONDENIM AEON Mall Hà Đông",
    province: "Hà Nội",
    district: "Quận Hà Đông",
    address: "Tầng 2, AEON Mall Hà Đông, Dương Nội, Hà Đông, Hà Nội",
    time: "10:00 - 22:00",
    phone: "02873066060",
    image: "/images/store/icondenim-aeon-mall-ha-dong.jpg",
    mapLink: "https://maps.app.goo.gl/XuYh3LZNNZgcbiSQ9",
    isNew: true,
    isOpen: true,
  },
  {
    id: "icondenim-chua-boc",
    name: "ICONDENIM Chùa Bộc",
    province: "Hà Nội",
    district: "Quận Đống Đa",
    address: "72 Chùa Bộc, Quang Trung, Đống Đa, Hà Nội",
    time: "08:30 - 22:00",
    phone: "02873066060",
    image: "/images/store/icondenim-chua-boc.jpg",
    mapLink: "https://maps.app.goo.gl/DAYJYGNGtuAjf7in6",
    isNew: false,
    isOpen: true,
  },
  {
    id: "icondenim-le-duan-da-nang",
    name: "ICONDENIM Lê Duẩn",
    province: "Đà Nẵng",
    district: "Quận Thanh Khê",
    address: "332 Lê Duẩn, Tân Chính, Thanh Khê, Đà Nẵng",
    time: "08:30 - 22:00",
    phone: "02873066060",
    image: "/images/store/icondenim-le-duan-da-nang.jpg",
    mapLink: "https://maps.app.goo.gl/nReHaLbUDKPgAjb29",
    isNew: true,
    isOpen: true,
  },
  {
    id: "icondenim-pham-van-thuan",
    name: "ICONDENIM Phạm Văn Thuận",
    province: "Đồng Nai",
    district: "Biên Hòa",
    address: "1357 Phạm Văn Thuận, Thống Nhất, Biên Hòa, Đồng Nai",
    time: "08:30 - 22:00",
    phone: "02873066060",
    image: "/images/store/icondenim-pham-van-thuan.jpg",
    mapLink: "https://maps.app.goo.gl/vKCGdaxuqAkXcDacA",
    isNew: false,
    isOpen: true,
  },
  {
    id: "icondenim-can-tho",
    name: "ICONDENIM Cần Thơ",
    province: "Cần Thơ",
    district: "Quận Ninh Kiều",
    address: "56 Nguyễn Trãi, Thới Bình, Ninh Kiều, Cần Thơ",
    time: "08:30 - 22:00",
    phone: "02873066060",
    image: "/images/store/icondenim-can-tho.jpg",
    mapLink: "https://maps.app.goo.gl/xnCjy3vgbaYmAwkc6",
    isNew: true,
    isOpen: true,
  },
  {
    id: "icondenim-vung-tau",
    name: "ICONDENIM Vũng Tàu",
    province: "Bà Rịa - Vũng Tàu",
    district: "TP. Vũng Tàu",
    address: "156 Ba Cu, Phường 4, TP. Vũng Tàu",
    time: "08:30 - 22:00",
    phone: "02873066060",
    image: "/images/store/icondenim-vung-tau.jpg",
    mapLink: "https://maps.app.goo.gl/r9fGqSgXo9L9zXo98",
    isNew: false,
    isOpen: true,
  },
];
